### ISSUE TITLE
Problem instanciating the toolbar Ypositions is empty

### ISSUE THREAD

**Issue by LeonardoFloriano** [SalehTZ/playable_toolbar_flutter#1]
Hello, i am having an issue with the toolbar in the moment that i instanciate it:
![image](https://user-images.githubusercontent.com/98328413/182441772-b79aefd9-8e2a-4f0d-90e7-fc0bfae101e8.png)

it is breaking on this line, saying that the yposition list is empty.

![image](https://user-images.githubusercontent.com/98328413/182441932-cdafadee-735e-4bab-af86-687f93b730a9.png)
![image](https://user-images.githubusercontent.com/98328413/182441962-bc3cf7df-ab51-41ae-82a7-667f05046a3f.png)

Those are the functions to return the itens, tried with 2, 3 itens but withou sucess.

i think the yposition list is clearing every tick of the instance of the state.

**Comment by SalehTZ** [comment]
This Issue is now fixed. Just upgrade the package to version 0.0.2 and enjoy.
